### ISSUE TITLE
Bot failing to Output

### ISSUE THREAD

**Issue by Delukatio** [galaxy119/PlayerStats#6]
While i'm sure I missed something painfully obvious, the bot appears to be unable to properly output.

When promoted with !stats (after !sync as been properly used), the bot returns with 'No stats found'.

The bot has the right location and the files do exist but it fails to withdraw the values.

The CLI for the bot follows:

> root@vultr:~/.config/EXILED/Plugins/PlayerStats# mono PlayerStatsBot.exe
> 03:27:05 Discord     Discord.Net v2.1.1 (API v6)
> 03:27:06 Gateway     Connecting
> 03:27:07 Gateway     Connected
> 03:27:07 Gateway     Ready
> 1
> ~/.config/Plugins/PlayerStats/76561198343950512@steam.txt
> 1
> ~/.config/Plugins/PlayerStats/76561198182166615@steam.txt

**Comment by galaxy119** [comment]
Do the stats files in .config/Plugins/PlayerStats exist?

Keep in mind, their location changed with the update to Exiled 2.0, and the stats files default to .config/EXILED/Plugins/PlayerStats

The bot was never updated with this new config location being set by default since there was no real reason to recompile the bot, you just change the path in it's config.

**Comment by Delukatio** [comment]
The stats files exist and i've changed the bot's location to their location. It just doesn't seem to properly load the contents of the files.

**Comment by jamgallACE** [comment]
It's a little late and you might have sorted this by now, but I had the same problem. In the stats file: .config/EXILED/Plugins/PlayerStats , you should have a backslash after playerstats, so it should be this:

.config/EXILED/Plugins/PlayerStats/
Hope this helps!

**Comment by tabgh708** [comment]
Basically, the path must be changed and used.  ₩ Not this / This one
